import SwiftUI

let roboticsBrand = Brand(
    appStoreName: "JB Robotics",
    displayName: "JB Robotics",
    navigationTitle: "JB Robotics",
    titlePrefix: "JB",
    titleBody: "Robotics",
    subtitle: "decoding robots & autonomy",
    tagline: nil,
    entryNoun: "entries",
    dataResource: "glossary_robotics",
    primaryColor: Color(red: 0.878, green: 0.416, blue: 0.106),       // #E06A1B signal amber
    primaryDarkColor: Color(red: 0.710, green: 0.325, blue: 0.059),   // #B5530F deeper amber
    bgColor: PGColors.bg,
    urlScheme: "robotics",
    aboutParagraphs: [
        "JB Robotics is a generalist's reference for the language of robots, autonomy, and embodied AI — the jargon you meet in the humanoid race, self-driving news, factory-automation pitches, and robotics research. It spans the robot itself (mechanics, actuators, kinematics), the autonomy stack (sensing, perception, control, planning, and the learning that now drives physical action), and the deployed world: autonomous vehicles, drones, the factory floor, and the companies building it.",
        "Entries summarise publicly available material from robotics standards bodies, research labs, open-source projects, and platform makers. They are written for orientation in plain English, not as engineering, safety, or investment guidance."
    ],
    aboutDisclaimer: "Educational reference. Not engineering, safety, or investment advice.",
    aboutSources: [
        BrandSource(
            heading: "Standards & government",
            items: ["IEEE RAS", "NIST", "ISO", "SAE International", "FAA"]
        ),
        BrandSource(
            heading: "Software & platforms",
            items: ["ROS", "Open Robotics", "MoveIt", "Gazebo", "NVIDIA Isaac"]
        ),
        BrandSource(
            heading: "Research & industry",
            items: ["arXiv", "DARPA", "NASA", "IFR"]
        ),
        BrandSource(
            heading: "Makers",
            items: ["Boston Dynamics"]
        )
    ],
    lenses: [
        LensConfig(
            id: "basics",
            glyph: "B",
            title: "Basics",
            subtitle: "Foundational robotics vocabulary",
            kind: .allowlist([
                "Robot",
                "Robotics",
                "Embodied intelligence",
                "Autonomy",
                "Levels of autonomy",
                "End-effector",
                "Mapping",
                "Kinematics",
                "Dynamics",
                "Dexterity",
                "Navigation",
                "Trajectory",
                "Actuation",
                "Sensing",
                "Real-time",
                "Accuracy",
                "Human-robot interaction",
                "Swarm robotics",
                "Agent",
                "Robot Operating System",
                "Simulation",
                "Foundation model",
                "Collision avoidance",
                "Soft robotics",
                "Uncanny valley",
                "Haptics",
                "Vision",
                "Mechatronics",
                "Automation",
                "Safety",
                "Self-driving",
                "Drone",
                "Three Laws of Robotics",
                "Android",
                "Service robotics",
                "Industrial robotics",
                "Dull, dirty, dangerous",
                "Degrees of freedom",
                "Workspace",
                "Link",
                "Joint",
                "Revolute joint",
                "Prismatic joint",
                "Chassis",
                "Reach",
                "Actuator",
                "Electric motor",
                "DC motor",
                "Brushless DC motor",
                "Stepper motor",
                "Servomotor",
                "Linear actuator",
                "Gearbox",
                "Hydraulic actuator",
                "Pneumatic actuator",
                "Encoder",
                "Pose",
                "Forward kinematics",
                "Inverse kinematics",
                "Center of mass",
                "Latency",
                "Edge computing",
                "Graphics processing unit",
                "Microcontroller",
                "Embedded system",
                "Lithium-ion battery",
                "Locomotion",
                "Odometry",
                "Legged locomotion",
                "Bipedal locomotion",
                "Quadrupedal locomotion",
                "Gait",
                "Wheeled locomotion",
                "Manipulator",
                "Manipulation",
                "Grasping",
                "Gripper",
                "Robotic hand",
                "Pick and place",
                "Pose estimation",
                "Autonomous mobile robot",
                "Automated guided vehicle",
                "Humanoid robot",
                "Quadruped robot",
                "Wheeled robot",
                "Articulated robot",
                "Cobot",
                "Mobile manipulator",
                "Unmanned aerial vehicle",
                "Exoskeleton",
                "Surgical robot",
                "Self-driving car",
                "Robotaxi",
                "Sensor fusion",
                "Calibration",
                "Sensor",
                "Inertial measurement unit",
                "Accelerometer",
                "Gyroscope",
                "Camera",
                "Depth camera",
                "LiDAR",
                "Point cloud",
                "Radar",
                "Global Navigation Satellite System",
                "Field of view",
                "Localization",
                "Perception",
                "Computer vision",
                "SLAM",
                "Kalman filter",
                "Object detection",
                "Obstacle detection",
                "HD map",
                "Control loop",
                "Force control",
                "Feedback control",
                "PID controller",
                "Setpoint",
                "Model predictive control",
                "Position control",
                "Torque control",
                "Motion planning",
                "Obstacle avoidance",
                "Waypoint",
                "Path planning",
                "A* search",
                "Digital twin",
                "Sim-to-real",
                "ROS",
                "ROS 2",
                "URDF",
                "Physics engine",
                "World model",
                "Teleoperation",
                "Policy",
                "Reinforcement learning",
                "Imitation learning",
                "Vision-language-action model",
                "Robot foundation model",
                "Embodied AI",
                "Neural network",
                "Transformer",
                "Operational design domain",
                "Autonomous vehicle",
                "SAE levels of driving automation",
                "Advanced driver-assistance systems",
                "Adaptive cruise control",
                "Automatic emergency braking",
                "Quadcopter",
                "eVTOL",
                "Autopilot",
                "Propeller",
                "Drone delivery",
                "Collaborative robot",
                "Industry 4.0",
                "Industrial automation",
                "Programmable logic controller",
                "Teach pendant",
                "Computer numerical control",
                "Machine vision",
                "Emergency stop",
                "Boston Dynamics",
                "Spot",
                "Tesla Optimus",
                "Waymo",
                "DJI",
                "iRobot",
                "Human-in-the-loop",
                "Return on investment",
            ])
        ),
        LensConfig(
            id: "robot",
            glyph: "R",
            title: "The Robot",
            subtitle: "Body, motion & power",
            kind: .categoryFilter(
                categories: [
                    "Mechanics & Structures", "Actuation & Drives",
                    "Kinematics & Dynamics", "Power & Compute",
                    "Locomotion", "Manipulation", "Form Factors"
                ],
                excludedTerms: []
            )
        ),
        LensConfig(
            id: "senseControl",
            glyph: "S",
            title: "Sense & Control",
            subtitle: "The perception–action stack",
            kind: .categoryFilter(
                categories: [
                    "Sensing", "Perception", "Control",
                    "Planning & Navigation", "Software & Simulation"
                ],
                excludedTerms: []
            )
        ),
        LensConfig(
            id: "embodiedAI",
            glyph: "E",
            title: "Embodied AI",
            subtitle: "Learning that drives physical action",
            kind: .categoryFilter(
                categories: ["Learning & Embodied AI"],
                excludedTerms: []
            )
        ),
        LensConfig(
            id: "systems",
            glyph: "I",
            title: "Systems & Industry",
            subtitle: "The deployed world",
            kind: .categoryFilter(
                categories: [
                    "Autonomous Vehicles", "Aerial & Drones",
                    "Industrial Automation", "Safety & Standards",
                    "Companies & Platforms", "Industry & Deployment"
                ],
                excludedTerms: []
            )
        )
    ],
    accentTint: nil,
    sourceURLs: [
        // Standards & government
        "IEEE RAS":         URL(string: "https://www.ieee-ras.org")!,
        "IEEE":             URL(string: "https://www.ieee.org")!,
        "NIST":             URL(string: "https://www.nist.gov")!,
        "ISO":              URL(string: "https://www.iso.org")!,
        "SAE International": URL(string: "https://www.sae.org")!,
        "SAE":              URL(string: "https://www.sae.org")!,
        "FAA":              URL(string: "https://www.faa.gov")!,
        // Software & platforms
        "ROS":              URL(string: "https://www.ros.org")!,
        "Open Robotics":    URL(string: "https://www.openrobotics.org")!,
        "MoveIt":           URL(string: "https://moveit.ai")!,
        "Gazebo":           URL(string: "https://gazebosim.org")!,
        "NVIDIA Isaac":     URL(string: "https://developer.nvidia.com/isaac")!,
        "NVIDIA":           URL(string: "https://www.nvidia.com")!,
        // Research & industry
        "arXiv":            URL(string: "https://arxiv.org/list/cs.RO/recent")!,
        "DARPA":            URL(string: "https://www.darpa.mil")!,
        "NASA":             URL(string: "https://www.nasa.gov")!,
        "IFR":              URL(string: "https://ifr.org")!,
        // Makers
        "Boston Dynamics":  URL(string: "https://www.bostondynamics.com")!
    ]
)
